config/routes.rb
Todolist::Application.routes.draw do
  root :to => "navicontroller#home"
  get "/help", :to => "navicontroller#help", :as => :help
  get "/tasklists/destroy_all", :to => "tasklists#destroy_all", :as => :del_all
  post "/tasklists/check_task/:id", :to => "tasklists#check_task", :as => :check_task
  get "/tasklists/completed", :to => "tasklists#complete", :as => :completed_tasks
  resources :tasklists
end

app/models/tasklist.rb
class Tasklist < ActiveRecord::Base
	def check_task(id)
		Tasklist.update(id, :is_completed => true)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/navicontroller_controller.rb
class NavicontrollerController < ApplicationController
  def home
  end

  def help
  end
end

app/controllers/tasklists_controller.rb
class TasklistsController < ApplicationController
  before_action :set_tasklist, only: [:show, :edit, :update, :destroy]
  skip_before_filter :verify_authenticity_token

  # GET /tasklists
  # GET /tasklists.json
  def index
    @tasklists = Tasklist.all
  end

  def check_task
    Tasklist.find(params[:id]).check_task(params[:id])
    redirect_to tasklists_path
  end

  def complete
    @tasklists = Tasklist.find(:all, :conditions => {:is_completed => true})
  end

  # GET /tasklists/1
  # GET /tasklists/1.json
  def show
  end

  # GET /tasklists/new
  def new
    @tasklist = Tasklist.new
  end

  # GET /tasklists/1/edit
  def edit
  end

  # POST /tasklists
  # POST /tasklists.json
  def create
    @tasklist = Tasklist.new(tasklist_params)

    respond_to do |format|
      if @tasklist.save
        format.html { redirect_to @tasklist, notice: 'Tasklist was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tasklist }
      else
        format.html { render action: 'new' }
        format.json { render json: @tasklist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasklists/1
  # PATCH/PUT /tasklists/1.json
  def update
    respond_to do |format|
      if @tasklist.update(tasklist_params)
        format.html { redirect_to @tasklist, notice: 'Tasklist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tasklist.errors, status: :unprocessable_entity }
      end
    end
  end
  def destroy_all
    Tasklist.destroy_all
    redirect_to tasklists_path
  end

  # DELETE /tasklists/1
  # DELETE /tasklists/1.json
  def destroy
    @tasklist.destroy
    respond_to do |format|
      format.html { redirect_to tasklists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tasklist
      @tasklist = Tasklist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tasklist_params
      params.require(:tasklist).permit(:name, :category, :is_completed, :date_todo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/navicontroller_helper.rb
module NavicontrollerHelper
end

app/helpers/tasklists_helper.rb
module TasklistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todolist</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default" role="navigation">
    <ul class="nav navbar-nav">
      <li><%= link_to 'Home', root_path %></li>
      <li><%= link_to 'Help', help_path %></li>
      <li><%= link_to 'Tasks', tasklists_path %></li>
    </ul>
  </nav>
  <%= yield %>
  <footer>
      Franco Zarate and Merlyn Patricio 2014
  </footer>
</body>
</html>

app/views/navicontroller/help.html.erb
<h1>To Do List</h1>

<h1>1. New Tasklist</h1>
<h1>2. Fill in the name, category, is completed, and date to do</h1>

<h1>3. Create Tasklist!</h1>

<h1>4. You're done!!</h1>

app/views/navicontroller/home.html.erb
<h1>To Do List</h1>
<h1>We are studying CS 21b under Andrei Navarro</h1>

app/views/tasklists/_form.html.erb
<%= form_for(@tasklist) do |f| %>
  <% if @tasklist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tasklist.errors.count, "error") %> prohibited this tasklist from being saved:</h2>

      <ul>
      <% @tasklist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :is_completed %><br>
    <%= f.check_box :is_completed %>
  </div>
  <div class="field">
    <%= f.label :date_todo %><br>
    <%= f.date_select :date_todo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tasklists/complete.html.erb
<h1>Completed Tasks</h1>
  <ul class="list-group">
    <% @tasklists.each do |tasklist| %>  
      <li class="list-group-item">
        <%= tasklist.name %>
      </li>
    <% end %>
  </ul>
<br>

<%= link_to 'New Tasklist', new_tasklist_path %>

app/views/tasklists/edit.html.erb
<h1>Editing tasklist</h1>

<%= render 'form' %>

<%= link_to 'Show', @tasklist %> |
<%= link_to 'Back', tasklists_path %>

app/views/tasklists/index.html.erb
<h1>Listing tasklists</h1>
  <ul class="list-group">
    <% @tasklists.each do |tasklist| %>  
      <li class="list-group-item">
        <form action="/tasklists/check_task/<%= tasklist.id %>" method="post" id="task<%= tasklist.id %>">
        <input type="hidden" name="id" value="<%= tasklist.id %>">
        <% if tasklist.is_completed %>
          <input name="taskcheckbox" type="checkbox" id="<%= tasklist.id %>" checked="checked">
          <del><%= tasklist.name %></del>
        <% else %>
          <input name="taskcheckbox" type="checkbox" id="<%= tasklist.id %>" onclick="$('#task<%= tasklist.id %>').submit();">
          <%= tasklist.name %>
        <% end %>
        </form>
      </li>
    <% end %>
  </ul>
<br>
<%= link_to 'Clear Tasklist', del_all_path %>
<%= link_to 'New Tasklist', new_tasklist_path %>

app/views/tasklists/new.html.erb
<h1>New tasklist</h1>

<%= render 'form' %>

<%= link_to 'Back', tasklists_path %>

app/views/tasklists/show.html.erb
<p id="notice"><%= notice %></p>



<p>
  <strong>Name:</strong>
  <%= @tasklist.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @tasklist.category %>
</p>

<p>
  <strong>Is completed:</strong>
  <%= @tasklist.is_completed %>
</p>

<p>
  <strong>Date todo:</strong>
  <%= @tasklist.date_todo %>
</p>

<%= link_to 'Edit', edit_tasklist_path(@tasklist) %> |
<%= link_to 'Back', tasklists_path %>